
apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
spec:
  containers:
  - name: wordpress-container
    image: wordpress:5.7-php7.4-apache
    ports:
    - containerPort: 80
      name: wordpress
  
